{
  "$schema": "https://raw.githubusercontent.com/earendil-works/pi/main/packages/coding-agent/src/modes/interactive/theme/theme-schema.json",
  "name": "omarchy-system",
  "vars": {
    "background": "{{ background }}",
    "foreground": "{{ foreground }}",
    "accent": "{{ accent }}",
    "selectionBackground": "{{ selection_background }}",
    "selectionForeground": "{{ selection_foreground }}",
    "selectedBackground": "{{ mix background accent 24% }}",
    "color0": "{{ background }}",
    "color1": "{{ red }}",
    "color2": "{{ green }}",
    "color3": "{{ yellow }}",
    "color4": "{{ blue }}",
    "color5": "{{ magenta }}",
    "color6": "{{ cyan }}",
    "color7": "{{ foreground }}",
    "color8": "{{ muted }}",
    "color9": "{{ bright_red }}",
    "color10": "{{ bright_green }}",
    "color11": "{{ bright_yellow }}",
    "color12": "{{ bright_blue }}",
    "color13": "{{ bright_magenta }}",
    "color14": "{{ bright_cyan }}",
    "color15": "{{ bright_foreground }}",
    "panel": "{{ mix background foreground 7% }}",
    "panelAlt": "{{ mix background accent 11% }}",
    "panelPending": "{{ mix background accent 14% }}",
    "panelSuccess": "{{ mix background green 14% }}",
    "panelError": "{{ mix background red 14% }}",
    "searchBackground": "{{ mix background yellow 26% }}",
    "border": "{{ mix background accent 34% }}",
    "borderMuted": "{{ mix background foreground 18% }}",
    "mutedText": "{{ mix foreground background 32% }}",
    "dimText": "{{ mix foreground background 52% }}"
  },
  "colors": {
    "accent": "accent",
    "border": "border",
    "borderAccent": "accent",
    "borderMuted": "borderMuted",
    "success": "color2",
    "error": "color1",
    "warning": "color3",
    "muted": "mutedText",
    "dim": "dimText",
    "text": "foreground",
    "thinkingText": "mutedText",
    "selectedBg": "selectedBackground",
    "scrollbarTrack": "borderMuted",
    "scrollbarThumb": "accent",
    "searchMatchBg": "searchBackground",
    "searchMatchText": "color15",
    "userMessageBg": "panel",
    "userMessageText": "foreground",
    "customMessageBg": "panelAlt",
    "customMessageText": "foreground",
    "customMessageLabel": "color14",
    "toolPendingBg": "panelPending",
    "toolSuccessBg": "panelSuccess",
    "toolErrorBg": "panelError",
    "toolTitle": "color14",
    "toolOutput": "foreground",
    "mdHeading": "color13",
    "mdLink": "color12",
    "mdLinkUrl": "dimText",
    "mdCode": "color14",
    "mdCodeBlock": "foreground",
    "mdCodeBlockBorder": "borderMuted",
    "mdQuote": "mutedText",
    "mdQuoteBorder": "accent",
    "mdHr": "borderMuted",
    "mdListBullet": "accent",
    "toolDiffAdded": "color10",
    "toolDiffRemoved": "color9",
    "toolDiffContext": "mutedText",
    "syntaxComment": "dimText",
    "syntaxKeyword": "color5",
    "syntaxFunction": "color12",
    "syntaxVariable": "foreground",
    "syntaxString": "color2",
    "syntaxNumber": "color11",
    "syntaxType": "color14",
    "syntaxOperator": "color13",
    "syntaxPunctuation": "mutedText",
    "thinkingOff": "borderMuted",
    "thinkingMinimal": "mutedText",
    "thinkingLow": "color4",
    "thinkingMedium": "accent",
    "thinkingHigh": "color3",
    "thinkingXhigh": "color1",
    "thinkingMax": "color9",
    "bashMode": "color3"
  },
  "export": {
    "pageBg": "{{ background }}",
    "cardBg": "{{ mix background foreground 7% }}",
    "infoBg": "{{ mix background accent 11% }}"
  }
}
